name: Format-Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: clang-format
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '15'
